export const allTags = [
  {
    _id: "f1",
    name: "Folder 1",
    isFolder: true,
    parent: null,
    ancestors: [],
  },
  {
    _id: "f2",
    name: "Folder 2",
    isFolder: true,
    parent: null,
    ancestors: [],
  },
  {
    _id: "f3",
    name: "Folder 3",
    isFolder: true,
    parent: null,
    ancestors: [],
  },
  {
    _id: "f4",
    name: "Folder 4",
    isFolder: true,
    parent: "f1",
    ancestors: ["f1"],
  },
  {
    _id: "f5",
    name: "Folder 5",
    isFolder: true,
    parent: "f2",
    ancestors: ["f2"],
  },
  {
    _id: "f6",
    name: "Folder 6",
    isFolder: true,
    parent: "f4",
    ancestors: ["f4", "f1"],
  },
  {
    _id: "f7",
    name: "Folder 7",
    isFolder: true,
    parent: "f5",
    ancestors: ["f5", "f2"],
  },
  {
    _id: "t1",
    name: "Tag 1",
    isFolder: false,
    parent: null,
    ancestors: [],
  },
  {
    _id: "t2",
    name: "Tag 2",
    isFolder: false,
    parent: null,
    ancestors: [],
  },
  {
    _id: "t3",
    name: "Tag 3",
    isFolder: false,
    parent: "f1",
    ancestors: ["f1"],
  },
  {
    _id: "t4",
    name: "Tag 4",
    isFolder: false,
    parent: "f1",
    ancestors: ["f1"],
  },
  {
    _id: "t5",
    name: "Tag 5",
    isFolder: false,
    parent: "f2",
    ancestors: ["f2"],
  },
  {
    _id: "t6",
    name: "Tag 6",
    isFolder: false,
    parent: "f4",
    ancestors: ["f4", "f1"],
  },
  {
    _id: "t7",
    name: "Tag 7",
    isFolder: false,
    parent: "f5",
    ancestors: ["f5", "f2"],
  },
  {
    _id: "t8",
    name: "Tag 8",
    isFolder: false,
    parent: "f3",
    ancestors: ["f3"],
  },
];
